version: '3.8'

services:
  app:
    image: mastilovic/rekreativ:latest
    hostname: rekreativ
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DB_HOST=mysql
      - USERNAME=root
      - PASSWORD=root
      - DB_NAME=rekreativdb
  mysql:
    image: mysql:5.7
    restart: on-failure
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=rekreativdb
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10