server:
  port: '8080'

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rekreativ
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect