spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/rekreativ
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop
server:
  port: '8080'