version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
#    container_name: mysql
    restart: on-failure
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: rekreativdb
      MSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
#    healthcheck:
#      test: [ "CMD", "mysql", "ping", "-h", "localhost" ]
#      timeout: 10s
#      retries: 10